
#' @title Get the
#'   
#' @param xds_obj an **`xds`** model object
#' @param i the host species index
#' 
#' @export
get_EIR = function(xds_obj, i=1){
  xds_obj$outputs$orbits$XH[[i]]$eir
}

#' Plot the EIR *vs.* time
#'
#' @param xds_obj a list that defines an `ramp.xds` model (*e.g.*,  generated by `ramp.xds::xds_setup()`)
#' @param i the host species index
#' @param clrs a vector of colors
#' @param llty an integer (or integers) to set the `lty` for plotting
#' @param add a logical: plot axes only if FALSE
#'
#' @export
xds_plot_EIR <- function(xds_obj, i=1, clrs="black", llty=1, add=FALSE){
  times = xds_obj$outputs$time
  EIR = get_EIR(xds_obj, i)

  if(add==FALSE){
      plot(times, 0*times, type = "n",
           xlab = "Time", ylab = "dEIR", ylim = range(0, EIR))
  }
  xds_lines_EIR(times, EIR, xds_obj$nStrata[i], clrs, llty)
}

#' Add lines for the EIR *vs.* time
#'
#' @param times the time
#' @param EIR the entomological inoculation rate
#' @param nStrata the number of human / host population strata
#' @param clrs a vector of colors
#' @param llty an integer (or integers) to set the `lty` for plotting
#'
#' @export
xds_lines_EIR <- function(times, EIR, nStrata, clrs="black", llty=1){
  if(nStrata==1)
    graphics::lines(times, EIR, col=clrs, lty = llty)
  if(nStrata>1){
    if(length(clrs)==1) clrs=rep(clrs, nStrata)
    if(length(llty)==1) llty=rep(llty, nStrata)
    for(i in 1:nStrata)
      graphics::lines(times, EIR[,i], col=clrs[i], lty = llty)
  }

}

#' Plot the annualized EIR *vs.* time
#'
#' @param xds_obj a list that defines an `ramp.xds` model (*e.g.*,  generated by `ramp.xds::xds_setup()`)
#' @param i the host species index
#' @param clrs a vector of colors
#' @param llty an integer (or integers) to set the `lty` for plotting
#' @param stable a logical: set to FALSE for `orbits` and FALSE for `stable_orbits`
#' @param add a logical: plot axes only if FALSE
#'
#' @export
xds_plot_aEIR <- function(xds_obj, i=1, clrs="black", llty=1, stable=FALSE, add=FALSE){
  times = xds_obj$outputs$time
  EIR = get_EIR(xds_obj, i)

  aEIR = 365*EIR
  if(add==FALSE)
      plot(times, 0*times, type = "n", xlab = "Time", ylab = "aEIR", ylim = range(0, aEIR))

  xds_lines_EIR(times, aEIR, xds_obj$nStrata[i], clrs, llty)
}

#' Plot the prevalence / parasite rate (PR) from a model of human infection and immunity
#'
#' @param xds_obj a list that defines an `ramp.xds` model (*e.g.*,  generated by `xds_setup()`)
#' @param i the host species index
#' @param clrs a vector of colors
#' @param llty an integer (or integers) that specifies `lty` for plotting
#' @param add a logical: plot axes only if FALSE
#'
#' @export
xds_plot_PR = function(xds_obj, i=1, clrs="black", llty=1, add=FALSE){
  terms = xds_obj$outputs$orbits$XH[[1]]
  times = xds_obj$outputs$time
  
  tm = xds_obj$outputs$time
  if(add==FALSE){
    plot(times, 0*times, type = "n", ylim = c(0,1),
         ylab = "Prevalence", xlab = "Time")
  }
  
  xds_lines_PR(times, terms$x, xds_obj$nStrata[i], clrs, llty)
}

#' Add lines for the prevalence / parasite rate (PR) from a model of human infection and immunity
#'
#' @param times the time
#' @param PR the computed parasite rate
#' @param nStrata the number of human / host population strata
#' @param clrs a vector of colors
#' @param llty an integer (or integers) that specifies `lty` for plotting
#'
#' @export
xds_lines_PR = function(times, PR, nStrata, clrs="black", llty=1){
  
  if(nStrata==1) graphics::lines(times, PR, col=clrs[1], lty = llty[1])
  if(nStrata>1){
    if (length(clrs)==1) clrs=rep(clrs, nStrata)
    if (length(llty)==1) llty=rep(llty, nStrata)
    for(i in 1:nStrata)
      graphics::lines(times, PR[,i], col=clrs[i], lty = llty[i])
  }
}


